### PR TITLE
[PATCH v12] Crypto 3GPP algorithms support

### PR DESCRIPTION
**Pull request by lumag**
For now this PR is mostly intended to test proposed 3GPP crypto algorithms API on top of DPDK implementation.

### CODE REVIEW

**Comment by lumag** [comment]
Basing on tests by @matiaselo and me:
- QAT driver does not support these algorithms if both length and offset are not bit aligned (and it is not expressed in any way in capabilities)
- Intel's Kasumi/Snow3G/ZUC drivers do not support these algorithms in bit mode in in-place mode (src mbuf = dst mbuf), which is used by ODP-DPDK.
I will check if it's possible to modify our code to use separate src and dst buffers (and thus use Intel's SSO drivers) after vacation.

**Comment by lumag** [comment]
@matiaselo I've updated this PR. Could you please rerun tests on QAT when you have time.

**Comment by matiaselo** [comment]
@lumag Validation tests are now passing with the new algorithms.

**Comment by lumag** [comment]
This PR should be now ready to be merged, after merger of API changes through main ODP repo.

**Comment by muvarov** [comment]
this has to be rebased to api-next branch.

**Comment by lumag** [comment]
@matiaselo note, `api-next` is the same as `master`.

**Comment by lumag** [comment]
rebased

**Comment by matiaselo** [comment]
> @matiaselo note, api-next is the same as master.

@muvarov The following commits are missing from the api-next branch:
- 9b2b5a969 validation: crypto: 3GPP crypto algorightms support
- 067a7054b validation: crypto: add support for bit mode algorithm testing
- f5b1a18c5 api: crypto: add bitstring operation capability
- 09da8929a api: crypto: provide definitions for 3GPP crypto algorithms
- 7c629241f api: comp: compression specification

Could you merge these patches directly from linux-generic or shall I create a PR?

**Comment by muvarov** [comment]
@matiaselo added commits above to api-next.

**Comment by lumag** [comment]
@matiaselo @muvarov rebased on top of updated `api-next`.

**Comment by muvarov** [comment]
merged.

**Pull request closed without merging**
