### PR TITLE
[PATCH v3] Crypto driver fixes

### PR DESCRIPTION
**Pull request by lumag**

### CODE REVIEW

**Comment by matiaselo** [comment]
The AES-XCBC validation tests are failing with QAT hardware. I'll send the debug logs.

**Comment by lumag** [comment]
@matiaselo it works with the OpenSSL and AESNI-MB drivers. I suspect that it is a bug in QAT PMD driver, as even with QAT only one test case is failing. I'll get to it afterwards.

**Comment by matiaselo** [comment]
> it works with the OpenSSL and AESNI-MB drivers. I suspect that it is a bug in QAT PMD driver, as even with QAT only one test case is failing. I'll get to it afterwards.

OK

**Comment by muvarov** [comment]
Merged.

**Pull request closed without merging**
