### PR TITLE
Fixes for configure

### PR DESCRIPTION
**Pull request by joseppc**
This fixes some minor issues I stumbled upon when building odp-dpdk on my system.

### CODE REVIEW

**Comment by matiaselo** [comment]
The PR #18 should fix these issues.

**Comment by joseppc** [comment]
You're right, most of it will be superseded by your PR (I wasn't aware of it at the time I wrote mine, sorry), but at least the last commit, or some form of it, should make it into #18 (and maybe into linux-generic too), I can send a PR on top of your branch.

**Comment by Bill-Fischofer-Linaro** [comment]
@joseppc Please rebase to resolve latest merge conflicts if this PR is still needed.

**Comment by joseppc** [comment]
sorry, I forgot to close this PR as we agreed last week.

**Pull request closed without merging**
