### PR TITLE
[PATCH v3] linux-dpdk: crypto: properly sort crypto capabilities

### PR DESCRIPTION
**Pull request by lumag**
ODP API specifies that cipher & auth capabilities are returned sorted.
Currently it is not the case, capabilities of different crypto devices
are just concatenated together. Sort them according to the API spec and
remove duplicates.

Signed-off-by: Dmitry Eremin-Solenikov <dmitry.ereminsolenikov@linaro.org>

### CODE REVIEW

**Comment by matiaselo** [comment]
Checkpatch still throws some minor warnings and most of the crypto validations tests fail with a QAT card:

```
Suite: odp_crypto_sync_inp
  Test: crypto_test_enc_alg_null ...passed
  Test: crypto_test_dec_alg_null ...passed
  Test: crypto_test_enc_alg_3des_cbc ...FAILED
    1. odp_crypto_test_inp.c:553  - rc == cipher_num
  Test: crypto_test_dec_alg_3des_cbc ...FAILED
    1. odp_crypto_test_inp.c:553  - rc == cipher_num
  Test: crypto_test_enc_alg_3des_cbc_ovr_iv ...FAILED
    1. odp_crypto_test_inp.c:553  - rc == cipher_num
  Test: crypto_test_dec_alg_3des_cbc_ovr_iv ...FAILED
    1. odp_crypto_test_inp.c:553  - rc == cipher_num
  Test: crypto_test_enc_alg_aes_cbc ...FAILED
    1. odp_crypto_test_inp.c:553  - rc == cipher_num
  Test: crypto_test_dec_alg_aes_cbc ...FAILED
    1. odp_crypto_test_inp.c:553  - rc == cipher_num
  Test: crypto_test_enc_alg_aes_cbc_ovr_iv ...FAILED
    1. odp_crypto_test_inp.c:553  - rc == cipher_num
  Test: crypto_test_dec_alg_aes_cbc_ovr_iv ...FAILED
    1. odp_crypto_test_inp.c:553  - rc == cipher_num
...
```

**Comment by lumag** [comment]
@matiaselo @psavol @Bill-Fischofer-Linaro 
Oh, I now understand, why this now fails. Previously it was easy to count 'Number of capability structures', because we just concatenated them. With this pach I've tried to remove duplicate capabilities (which is logical), but now it is not that easy to estimate number of caps in case of input array overflowing (because some caps might be removed, but we can not really calculate that in advance).
I might split this into several patches:
 - Just sort caps (and do not drop anything)
 - Drop duplicates (this PR)
 - Try to merge AAD fields (not implemented yet).

**Comment by lumag** [comment]
@matiaselo @psavol I've updated PR to include all capabilities (in other words, include duplicates). This should fix testing with QAT card. Also I've opened issue https://github.com/Linaro/odp/issues/652 to further discuss this.

**Comment by matiaselo** [comment]
> I've updated PR to include all capabilities (in other words, include duplicates). This should fix testing with QAT card. Also I've opened issue Linaro/odp#652 to further discuss this.

@lumag The patch works now with QAT cards. Please fix the remaining checkpatch warnings and I'll add reviewed tag.

**Comment by lumag** [comment]
@matiaselo done

**Comment by muvarov** [comment]
Merged.

**Pull request closed without merging**
