### PR TITLE
scripts: remove deprecated scripts

### PR DESCRIPTION
**Pull request by matiaselo**
Signed-off-by: Matias Elo <matias.elo@nokia.com>

### CODE REVIEW

**Comment by joseppc** [comment]
devbuild.sh seems to be referenced by OFP's own build scripts

**Comment by matiaselo** [comment]
@joseppc The OFP build script (and devbuild.sh) references to git.linaro.org/lng/check-odp.git, which is not maintained anymore(?). The OFP build script should probably be updated to use 'build-pktio-dpdk' script instead.

**Comment by joseppc** [comment]
@matiaselo check-odp is not maintained as far as I know. We'll have to take a look at OFP's build scripts, then.

**Comment by muvarov** [comment]
Merged.

**Pull request closed without merging**
