### PR TITLE
README.DPDK: update supported dpdk version

### PR DESCRIPTION
**Pull request by matiaselo**
Signed-off-by: Matias Elo <matias.elo@nokia.com>

### CODE REVIEW

**Comment by joseppc** [comment]
I don't know if we should take the opportunity to change the references to git.linaro.org for the github URL instead. I can do thart myself in another PR, of course.

**Comment by Bill-Fischofer-Linaro** [comment]
@joseppc Good catch. I only looked at the changes in the PR, but you're right we should change those references. I notice we also refer to check-odp, which we no longer use since Travis does that. Any opinions @muvarov? 

In any event, I'd think fixing those references would be better as a separate PR.

**Comment by matiaselo** [comment]
@joseppc if you have time a PR for fixing the repo references etc. would be gladly appreciated.

**Comment by joseppc** [comment]
@matiaselo will do

**Comment by muvarov** [comment]
Merged.

**Pull request closed without merging**
